### ISSUE TITLE
AmazonEKS_Karpenter_Controller_Policy - doesn't allow launch a new instance from template

### ISSUE THREAD

**Issue by rmalenko** [terraform-aws-modules/terraform-aws-iam#245]
AmazonEKS_Karpenter_Controller_Policy - doesn't allow launch a new instance from template has due to strict policy. I have found a solution, but ain't sure if the solution is perfect. So, there are changes in `./iam-role-for-service-accounts-eks/policies.tf `

two `actions = ["ec2:RunInstances"]` - merged into one due to removed 
```hcl
    condition {
      test     = "StringEquals"
      variable = "ec2:ResourceTag/${var.karpenter_tag_key}"
      values   = [var.karpenter_controller_cluster_id]
    }
```
and added:
```hcl
"arn:${local.partition}:ec2:*:${local.account_id}:key-pair/*",
"arn:${local.partition}:ec2:*:${local.account_id}:subnet/*",
```

Full part of [Karpenter Controller Policy](https://gist.github.com/rmalenko/e1c03bb5a747fd4fdfa86daf20e5fd01)

If someone has better ideas, let me know, please.

**Comment by bryantbiggs** [comment]
I'm not sure I quite follow what you are looking for. Yes there is a tag requirement that limits the permissions Karpenter receives so that it only has destructive permissions over the resources it creates. This tag is applied at the provisioner like:

```yaml
apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: default
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
    limits:
      resources:
        cpu: 1000
    provider:
      subnetSelector:
        karpenter.sh/discovery: ${local.name}
      securityGroupSelector:
        karpenter.sh/discovery: ${local.name}
      tags: 
        karpenter.sh/discovery: ${local.name} # <= This tag key:value
    ttlSecondsAfterEmpty: 30
```

**Comment by rmalenko** [comment]
As I understand this IAM rule prevent to launch new node by Karpenter from a template

```hcl
  statement {
    actions = ["ec2:RunInstances"]
    resources = [
      "arn:${local.partition}:ec2:*:${local.account_id}:launch-template/*",
      "arn:${local.partition}:ec2:*:${local.account_id}:security-group/*",
      "arn:${local.partition}:ec2:*:${coalesce(var.karpenter_subnet_account_id, local.account_id)}:subnet/*",
    ]

    condition {
      test     = "StringEquals"
      variable = "ec2:ResourceTag/${var.karpenter_tag_key}"
      values   = [var.karpenter_controller_cluster_id]
    }
  }
```

and this needs to launch a new node

```hcl
"arn:${local.partition}:ec2:*:${local.account_id}:key-pair/*",
"arn:${local.partition}:ec2:*:${local.account_id}:subnet/*",
```

My Provisioner is
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: criticaladdonsonly-karpenter
  spec:
    taints:
      - key: "${local.taints_key_criticaladdonsonly}"
        effect: NoSchedule
    labels:
      purpose: criticaladdonsonly
      managed-by: karpenter
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: "topology.kubernetes.io/zone" 
        operator: In
        values: ["${var.aws_region}a", "${var.aws_region}b"]
      - key: "kubernetes.io/arch" 
        operator: In
        values: ["arm64", "amd64"]
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: ["t3.micro", "t3.small", "t3.medium", "t3.large", "c5.xlarge", "c5.2xlarge", "c5.2xlarge", "m5.large", "m5.xlarge"]
    limits:
      resources:
        cpu: 100
        memory: 1000Gi
    provider:
      launchTemplate: "${aws_launch_template.karpenter.name}"
      subnetSelector:
        karpenter.sh/discovery: "private-${local.name}"

      tags:
        karpenter.sh/discovery: "${local.name}"
        Name: "criticaladdonsonly-${local.name}"
    ttlSecondsAfterEmpty: 30
```
