### ISSUE TITLE
IRSA module missing policy when using only  `attach_load_balancer_controller_targetgroup_binding_only_policy = true`

### ISSUE THREAD

**Issue by apamildner** [terraform-aws-modules/terraform-aws-iam#291]
## Description
When using the option `attach_load_balancer_controller_targetgroup_binding_only_policy = true`, a subset of the
policies are added that by the name of the argument should allow targetgroup binding to occur. This may have been true before, but as of AWS Load Balancer Controller `v2.4.4` installed via chart version `1.4.5` [here](https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller),  the policies are not enough any more. We also need these to be added:

```
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress"
```
More specifically, here is where they need to be added:
[here](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-role-for-service-accounts-eks/policies.tf#L870)

## How was this discovered
As described, deploy the AWS Load Balancer controller and then add a TargetGroupBinding.
Reading the logs from AWS Load Balancer controller pods we see there are authorization issues related to the above mentioned policies missing.
**TGB applied**
```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: networking
  name: traefik-service-external-http
spec:
  serviceRef:
    name: traefik-service-external
    port: 80
  targetGroupARN: <arn>
  targetType: instance
  networking:
    ingress:
      - from:
        - ipBlock:
            cidr: 0.0.0.0/0
        ports:
        - port: 30002 
          protocol: TCP
```
## Workaround
```hcl
module "load_balancer_controller" {
  source                                                          = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version                                                         = "~> v5.5.0"
  role_name                                                       = "aws-load-balancer-controller-${var.cluster_name}"
  attach_load_balancer_controller_targetgroup_binding_only_policy = true
  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-load-balancer-controller"]
    }
  }
}
# Temporary fix
resource "aws_iam_policy" "auth_revoke_sg_policy" {
  name        = "AuthorizeRevokeIngressSG"
  description = "Required when using targetGroupBinding inside EKS"

  policy = <<EOF
{
    "Statement": [
        {
            "Action": [
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        }
    ],
    "Version": "2012-10-17"
}
EOF
}

resource "aws_iam_role_policy_attachment" "attach_auth_revoke_sg_policy" {
  role       = module.load_balancer_controller.iam_role_name
  policy_arn = aws_iam_policy.auth_revoke_sg_policy.arn
}
```

I can submit a PR 👍
