### ISSUE TITLE
Insufficient permissions when using karpenter irsa without discovery tags

### ISSUE THREAD

**Issue by apamildner** [terraform-aws-modules/terraform-aws-iam#295]
## Description
The issue is described in the [PR](https://github.com/terraform-aws-modules/terraform-aws-iam/pull/294)

## Versions

- Module version [Required]:  v5.5.0

## Reproduction Code [Required]

1. Create `AWSNodeTemplate` like this
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    aws-ids: subnet-abc,subnet-xyz
  securityGroupSelector:
    aws-ids: sg-abc,sg-xyz
  tags:
    karpenter.sh/discovery/foo-cluster: foo-cluster
```
2. Make karpenter try to create a new node with a provisioner pointing to the above mentioned template
3. Make sure the security groups you try to use doesn't have the tag `karpenter.sh/discovery/foo-cluster: foo-cluster` instead refer to them with their ID's

## Expected behavior

The node comes up without a problem

## Actual behavior

The karpenter controller fails to run the instance, and instead gives me an UnAuthorizedError which it prints in the logs.
The message indicates that I miss the correct privilege to run `ec2:RunInstances` since the security group I try to use is missing the `ec2:ResourceTag/karpenter.sh/discovery/foo-cluster`.
