### ISSUE TITLE
Version 5.54.0 unavailable for all Terraform versions

### ISSUE THREAD

**Issue by bodgit** [terraform-aws-modules/terraform-aws-iam#556]
## Description

Version 5.54.0 doesn't seem to be available if you're running an older version of Terraform.

We're on Terraform 1.5.7 because reasons, and I can't see any version constraints in this module other than requiring `>= 1.0`.

Appreciate this might not be specific to this module.

## Versions

- Module version [Required]: 5.54.0

- Terraform version: 1.5.7

## Reproduction Code [Required]

```hcl
module "iam" {
  source  = "terraform-aws-modules/iam/aws"
  version = "5.54.0"
}
```

## Expected behavior

`terraform init` JFW.

## Actual behavior

Error stating 5.53.0 is the newest version.

Switch briefly to Terraform 1.11.2, `terraform init` now works. I'm not yet sure where the version cut-off is.

Edit: it's literally >= 1.6.0, so it seems you have to run a BSL-licensed Terraform to get new module versions

**Comment by frank-hopkin** [comment]
Reproduced on 1.10.1 in GitHub Actions

```yml
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.1

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ matrix.directory }}
```
